### ISSUE TITLE
File was not formatted by prettier

### ISSUE THREAD

**Issue by Unknow-max** [ikatyang/gulp-plugin-prettier#221]
Hi 👋,
For some unknow reason when I try to use prettier on my main.css file the plugin says:
`File Project\assets\styles\scss\main.css' was not formatted with Prettier`

See screenshot below:
![immagine](https://user-images.githubusercontent.com/59534318/84651069-a1a91280-af09-11ea-8bf6-bbebac17fe43.png)

And this is my gulp task:
```javascript

function scss() {
  return src("project/assets/styles/scss/**/*.scss")
    .pipe(sourcemaps.init())
    .pipe(sass({
      outputStyle: "expanded",
    }))
    .on("error", function(error) {
      notify.onError({
        title: "Error in SASS compilation",
        message: error.formatted + "\n Relative path " + error.relativePath + "\n",
        sound: false,
        icon: "C:\\Users\\limi2\\Desktop\\utili-template\\altro\\sass.svg",
      })(error);
      this.emit("end");
      return notify().write(error.messageOriginal);
    })
    .pipe(prefix())
    .pipe(prettier.format())
    .pipe(sourcemaps.write("./"))
    .pipe(dest("./project/assets/styles/css/"))
    .pipe(browserSync.stream());
}


```
Is there anything wrong with my task?

Version of prettier: 2.0.5
Version of the plugin: 2.0.1

**Comment by ikatyang** [comment]
The default reporter is `warning`, which prints warning for files that are different from Prettier formatting. You could disable the reporter by setting reporter as `none`, i.e., `prettier.format(undefined, { reporter: 'none' })`.
